//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ocad.Import {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.22")]
        public decimal EpsilonDistanceMM {
            get {
                return ((decimal)(this["EpsilonDistanceMM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("518.0")]
        public string RemoveDuplicateBridges_BridgeSymbolNumber {
            get {
                return ((string)(this["RemoveDuplicateBridges_BridgeSymbolNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.75")]
        public decimal RemoveDuplicateBridges_MinDistanceBetweenNonFacingBridgeEdgeMM {
            get {
                return ((decimal)(this["RemoveDuplicateBridges_MinDistanceBetweenNonFacingBridgeEdgeMM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.35")]
        public decimal RemoveDuplicateBridges_MinDistanceBetweenFacingBridgeEdgeMM {
            get {
                return ((decimal)(this["RemoveDuplicateBridges_MinDistanceBetweenFacingBridgeEdgeMM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public double RemoveDuplicateBridges_AngleEpsilonFullCirclePercentage {
            get {
                return ((double)(this["RemoveDuplicateBridges_AngleEpsilonFullCirclePercentage"]));
            }
        }
    }
}
